export const UPDATE_USERNAME = "UPDATE_USERNAME";
export const USERNAME_STATUS = "USERNAME_STATUS";
export const UPDATE_USERDETAILS = "UPDATE_USERDETAILS";
export const UPDATE_PUBLICREPOS = "UPDATE_PUBLICREPOS";
export const UPDATE_CHARTDATA = "UPDATE_CHARTDATA";
export const MODAL_STATUS = "MODAL_STATUS";
