export const UPDATE_USERNAME = "UPDATE_USERNAME";
export const INVALID_USERNAME = "INVALID_USERNAME";
export const UPDATE_USERDETAILS = "UPDATE_USERDETAILS";
export const UPDATE_PUBLICREPOS = "UPDATE_PUBLICREPOS";
